server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true        # Eureka서버로 부터 인스턴스들의 정보를 주기적으로 가져올 것인지의 속성
    register-with-eureka: true